### PR TITLE
Added Generative Adversarial Networks presentation and research papers.

### PR DESCRIPTION
**Pull request by jzhanson**

### CODE REVIEW

**Comment by remzr7** [comment]
You need to clean this up. What are there so many files?

Also, edit the _data/details.yml file

**Comment by jzhanson** [comment]
It has a lot of files because of the extra research papers I thought it would be a good idea to include

**Comment by remzr7** [comment]
Could you provide links to them in the description than upload the research papers, please?

Thanks Josh

**Comment by remzr7** [comment]
Furthermore, could you remove the README file and add your description to _data/details.yml file following the existing layout?

**Pull request closed without merging**
